FROM centos:7

RUN yum -y --enablerepo=extras install epel-release&& yum -y install wget make gcc openssl-devel bzip2-devel && yum install python3-pip -y  && yum -y groupinstall development && yum clean all && yum -y update
RUN yum -y update

ADD https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tgz .
RUN tar xzf Python-3.7.2.tgz

RUN cd Python-3.7.2 && ./configure --enable-optimizations
#RUN make altinstall
pip install --upgrade pip

#RUN pip install pyperformance

#RUN pyperformance venv create

#RUN sed 's/default=loops/default=10/' -i /venv/cpython3.8-*/lib/python3.8/site-packages/pyperf/_runner.py

#CMD while true; do pyperformance run --rigorous -o "py-$(date +%s).json"; done